spring:
  config:
    import: optional:classpath:secrets/prod/secret-prod.properties

  application:
    name: pontual-monitor-api

  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}?sslmode=require
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false

  main:
    banner-mode: console

  flyway:
    enabled: true
    schemas: public
    locations: classpath:db/migration

  cloud:
    openfeign:
      client:
        config:
          default:
            connectTimeout: 5000
            readTimeout: 5000
            loggerLevel: full

security:
  jwt:
    secret: ${JWT_SECRET}
    access-expiration-ms: 900000 #15 minutes
    refresh-expiration-ms: 604800000 #7 dias
    remember-refresh-expiration-ms: 1296000000 #15 dias
    cookie:
      secure: true
      same-site: "None"

springdoc:
  paths-to-exclude: /actuator/**, /error

server:
  servlet:
    context-path: /pontual/api/v1

sgman:
  client:
    unit: ${UNIT}
    url: https://get.api.sismetro.com
  token:
    solicitante: ${KEY_SOLICITANTES}
    patrimonio: ${KEY_PATRIMONIOS}

dashboard:
  daily:
    limit-to-24h: false

logging:
  level:
    feign: DEBUG
    org.springframework.security: INFO
