spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/pontualdb
    username: UserPontual
    password: 123456

  jpa:
    hibernate:
      ddl-auto: update

security:
  jwt:
    secret: No5JpJ2hqsbTrACMBLeASLjBq+t4RqI427skYce3CZA=

server:
  port: 8081